export interface KemenagHolidayPreset {
  name: string;
  date: string; // YYYY-MM-DD
  endDate?: string; // Optional YYYY-MM-DD
  isNational: boolean;
  description: string;
  year: number;
}

export const KEMENAG_HOLIDAYS_MASTER: KemenagHolidayPreset[] = [
  // ==========================================
  // TAHUN 2025
  // ==========================================
  {
    name: "Tahun Baru 2025 Masehi",
    date: "2025-01-01",
    isNational: true,
    description: "Hari Libur Nasional Tahun Baru Masehi",
    year: 2025,
  },
  {
    name: "Hari Amal Bhakti (HAB) Kemenag Ke-79",
    date: "2025-01-03",
    isNational: false,
    description: "Peringatan Hari Lahir Kementerian Agama RI",
    year: 2025,
  },
  {
    name: "Isra Mi'raj Nabi Muhammad SAW 1446 H",
    date: "2025-01-27",
    isNational: true,
    description: "Hari Libur Nasional Isra Mi'raj",
    year: 2025,
  },
  {
    name: "Tahun Baru Imlek 2576 Kongzili & Cuti Bersama",
    date: "2025-01-28",
    endDate: "2025-01-29",
    isNational: true,
    description: "Tahun Baru Imlek 2576 Kongzili & Cuti Bersama",
    year: 2025,
  },
  {
    name: "Libur Awal Ramadhan 1446 H",
    date: "2025-03-01",
    endDate: "2025-03-03",
    isNational: false,
    description: "Perkiraan Libur Awal Puasa Ramadhan Kalender Pendidikan Kemenag",
    year: 2025,
  },
  {
    name: "Hari Suci Nyepi (Tahun Baru Saka 1947)",
    date: "2025-03-28",
    endDate: "2025-03-29",
    isNational: true,
    description: "Hari Suci Nyepi & Cuti Bersama",
    year: 2025,
  },
  {
    name: "Hari Raya Idul Fitri 1446 H & Cuti Bersama",
    date: "2025-03-31",
    endDate: "2025-04-07",
    isNational: true,
    description: "Libur Nasional Hari Raya Idul Fitri 1446 H dan Cuti Bersama",
    year: 2025,
  },
  {
    name: "Wafat Yesus Kristus & Paskah",
    date: "2025-04-18",
    endDate: "2025-04-20",
    isNational: true,
    description: "Wafat Yesus Kristus dan Hari Paskah",
    year: 2025,
  },
  {
    name: "Hari Buruh Internasional",
    date: "2025-05-01",
    isNational: true,
    description: "Hari Buruh Internasional (May Day)",
    year: 2025,
  },
  {
    name: "Hari Raya Waisak 2569 BE & Cuti Bersama",
    date: "2025-05-12",
    endDate: "2025-05-13",
    isNational: true,
    description: "Hari Raya Waisak 2569 BE",
    year: 2025,
  },
  {
    name: "Kenaikan Yesus Kristus & Cuti Bersama",
    date: "2025-05-29",
    endDate: "2025-05-30",
    isNational: true,
    description: "Kenaikan Yesus Kristus dan Cuti Bersama",
    year: 2025,
  },
  {
    name: "Hari Lahir Pancasila",
    date: "2025-06-01",
    isNational: true,
    description: "Peringatan Hari Lahir Pancasila",
    year: 2025,
  },
  {
    name: "Hari Raya Idul Adha 1446 H & Cuti Bersama",
    date: "2025-06-06",
    endDate: "2025-06-09",
    isNational: true,
    description: "Hari Raya Idul Adha 1446 H dan Cuti Bersama",
    year: 2025,
  },
  {
    name: "1 Muharram / Tahun Baru Islam 1447 H",
    date: "2025-06-27",
    isNational: true,
    description: "Tahun Baru Islam 1447 Hijriyah",
    year: 2025,
  },
  {
    name: "Libur Akhir Tahun Ajaran / Kenaikan Kelas",
    date: "2025-06-30",
    endDate: "2025-07-12",
    isNational: false,
    description: "Libur Semester Genap / Akhir Tahun Ajaran Madrasah",
    year: 2025,
  },
  {
    name: "HUT Proklamasi Kemerdekaan RI Ke-80",
    date: "2025-08-17",
    isNational: true,
    description: "Hari Ulang Tahun Kemerdekaan Republik Indonesia",
    year: 2025,
  },
  {
    name: "Maulid Nabi Muhammad SAW 1447 H",
    date: "2025-09-05",
    isNational: true,
    description: "Peringatan Maulid Nabi Muhammad SAW",
    year: 2025,
  },
  {
    name: "Hari Santri Nasional 2025",
    date: "2025-10-22",
    isNational: false,
    description: "Peringatan Hari Santri Nasional Kementerian Agama RI",
    year: 2025,
  },
  {
    name: "Hari Guru Nasional 2025",
    date: "2025-11-25",
    isNational: false,
    description: "Peringatan Hari Guru Nasional Madrasah",
    year: 2025,
  },
  {
    name: "Libur Akhir Semester Ganjil Madrasah",
    date: "2025-12-22",
    endDate: "2026-01-02",
    isNational: false,
    description: "Libur Pembagian Rapor & Semester Ganjil TP 2025/2026",
    year: 2025,
  },
  {
    name: "Hari Raya Natal & Cuti Bersama",
    date: "2025-12-25",
    endDate: "2025-12-26",
    isNational: true,
    description: "Hari Raya Natal dan Cuti Bersama",
    year: 2025,
  },

  // ==========================================
  // TAHUN 2026
  // ==========================================
  {
    name: "Tahun Baru 2026 Masehi",
    date: "2026-01-01",
    isNational: true,
    description: "Hari Libur Nasional Tahun Baru Masehi",
    year: 2026,
  },
  {
    name: "Hari Amal Bhakti (HAB) Kemenag Ke-80",
    date: "2026-01-03",
    isNational: false,
    description: "Peringatan Hari Amal Bhakti Kementerian Agama Republik Indonesia",
    year: 2026,
  },
  {
    name: "Isra Mi'raj Nabi Muhammad SAW 1447 H",
    date: "2026-01-16",
    isNational: true,
    description: "Hari Libur Nasional Isra Mi'raj",
    year: 2026,
  },
  {
    name: "Tahun Baru Imlek 2577 Kongzili",
    date: "2026-02-17",
    isNational: true,
    description: "Tahun Baru Imlek 2577",
    year: 2026,
  },
  {
    name: "Libur Awal Ramadhan 1447 H",
    date: "2026-02-18",
    endDate: "2026-02-20",
    isNational: false,
    description: "Perkiraan Libur Awal Ramadhan 1447 H Kalender Madrasah",
    year: 2026,
  },
  {
    name: "Hari Suci Nyepi (Tahun Baru Saka 1948)",
    date: "2026-03-19",
    isNational: true,
    description: "Hari Libur Nasional Hari Suci Nyepi",
    year: 2026,
  },
  {
    name: "Hari Raya Idul Fitri 1447 H & Cuti Bersama",
    date: "2026-03-20",
    endDate: "2026-03-26",
    isNational: true,
    description: "Hari Raya Idul Fitri 1447 H dan Cuti Bersama",
    year: 2026,
  },
  {
    name: "Wafat Yesus Kristus",
    date: "2026-04-03",
    isNational: true,
    description: "Wafat Yesus Kristus (Jumat Agung)",
    year: 2026,
  },
  {
    name: "Hari Buruh Internasional",
    date: "2026-05-01",
    isNational: true,
    description: "Hari Buruh Internasional",
    year: 2026,
  },
  {
    name: "Kenaikan Yesus Kristus",
    date: "2026-05-14",
    isNational: true,
    description: "Hari Libur Nasional Kenaikan Yesus Kristus",
    year: 2026,
  },
  {
    name: "Hari Raya Idul Adha 1447 H & Cuti Bersama",
    date: "2026-05-27",
    endDate: "2026-05-29",
    isNational: true,
    description: "Hari Raya Idul Adha 1447 H",
    year: 2026,
  },
  {
    name: "Hari Raya Waisak 2570 BE",
    date: "2026-05-31",
    isNational: true,
    description: "Hari Raya Waisak 2570",
    year: 2026,
  },
  {
    name: "Hari Lahir Pancasila",
    date: "2026-06-01",
    isNational: true,
    description: "Hari Lahir Pancasila",
    year: 2026,
  },
  {
    name: "1 Muharram / Tahun Baru Islam 1448 H",
    date: "2026-06-16",
    isNational: true,
    description: "Tahun Baru Islam 1448 Hijriyah",
    year: 2026,
  },
  {
    name: "Libur Akhir Tahun Ajaran / Kenaikan Kelas",
    date: "2026-06-22",
    endDate: "2026-07-11",
    isNational: false,
    description: "Libur Semester Genap TP 2025/2026",
    year: 2026,
  },
  {
    name: "HUT Proklamasi Kemerdekaan RI Ke-81",
    date: "2026-08-17",
    isNational: true,
    description: "Hari Kemerdekaan Republik Indonesia",
    year: 2026,
  },
  {
    name: "Maulid Nabi Muhammad SAW 1448 H",
    date: "2026-08-25",
    isNational: true,
    description: "Maulid Nabi Muhammad SAW",
    year: 2026,
  },
  {
    name: "Hari Santri Nasional 2026",
    date: "2026-10-22",
    isNational: false,
    description: "Peringatan Hari Santri Nasional Kementerian Agama RI",
    year: 2026,
  },
  {
    name: "Hari Guru Nasional 2026",
    date: "2026-11-25",
    isNational: false,
    description: "Peringatan Hari Guru Nasional",
    year: 2026,
  },
  {
    name: "Hari Raya Natal & Cuti Bersama",
    date: "2026-12-25",
    endDate: "2026-12-26",
    isNational: true,
    description: "Hari Raya Natal dan Cuti Bersama",
    year: 2026,
  },
  {
    name: "Libur Akhir Semester Ganjil Madrasah",
    date: "2026-12-21",
    endDate: "2027-01-02",
    isNational: false,
    description: "Libur Semester Ganjil TP 2026/2027",
    year: 2026,
  },

  // ==========================================
  // TAHUN 2027
  // ==========================================
  {
    name: "Tahun Baru 2027 Masehi",
    date: "2027-01-01",
    isNational: true,
    description: "Tahun Baru Masehi 2027",
    year: 2027,
  },
  {
    name: "Hari Amal Bhakti (HAB) Kemenag Ke-81",
    date: "2027-01-03",
    isNational: false,
    description: "Peringatan Hari Amal Bhakti Kemenag RI",
    year: 2027,
  },
  {
    name: "Isra Mi'raj Nabi Muhammad SAW 1448 H",
    date: "2027-01-06",
    isNational: true,
    description: "Isra Mi'raj Nabi Muhammad SAW",
    year: 2027,
  },
  {
    name: "Tahun Baru Imlek 2578 Kongzili",
    date: "2027-02-06",
    isNational: true,
    description: "Tahun Baru Imlek 2578",
    year: 2027,
  },
  {
    name: "Libur Awal Ramadhan 1448 H",
    date: "2027-02-08",
    endDate: "2027-02-10",
    isNational: false,
    description: "Perkiraan Libur Awal Ramadhan 1448 H",
    year: 2027,
  },
  {
    name: "Hari Raya Idul Fitri 1448 H & Cuti Bersama",
    date: "2027-03-09",
    endDate: "2027-03-15",
    isNational: true,
    description: "Hari Raya Idul Fitri 1448 H dan Cuti Bersama",
    year: 2027,
  },
  {
    name: "Wafat Yesus Kristus",
    date: "2027-03-26",
    isNational: true,
    description: "Wafat Yesus Kristus",
    year: 2027,
  },
  {
    name: "Hari Suci Nyepi (Tahun Baru Saka 1949)",
    date: "2027-04-08",
    isNational: true,
    description: "Hari Suci Nyepi",
    year: 2027,
  },
  {
    name: "Hari Buruh Internasional",
    date: "2027-05-01",
    isNational: true,
    description: "Hari Buruh Internasional",
    year: 2027,
  },
  {
    name: "Kenaikan Yesus Kristus",
    date: "2027-05-06",
    isNational: true,
    description: "Kenaikan Yesus Kristus",
    year: 2027,
  },
  {
    name: "Hari Raya Idul Adha 1448 H & Cuti Bersama",
    date: "2027-05-16",
    endDate: "2027-05-18",
    isNational: true,
    description: "Hari Raya Idul Adha 1448 H",
    year: 2027,
  },
  {
    name: "Hari Raya Waisak 2571 BE",
    date: "2027-05-20",
    isNational: true,
    description: "Hari Raya Waisak 2571 BE",
    year: 2027,
  },
  {
    name: "Hari Lahir Pancasila",
    date: "2027-06-01",
    isNational: true,
    description: "Hari Lahir Pancasila",
    year: 2027,
  },
  {
    name: "1 Muharram / Tahun Baru Islam 1449 H",
    date: "2027-06-06",
    isNational: true,
    description: "Tahun Baru Islam 1449 Hijriyah",
    year: 2027,
  },
  {
    name: "Libur Akhir Tahun Ajaran / Kenaikan Kelas",
    date: "2027-06-21",
    endDate: "2027-07-10",
    isNational: false,
    description: "Libur Kenaikan Kelas & Semester Genap",
    year: 2027,
  },
  {
    name: "Maulid Nabi Muhammad SAW 1449 H",
    date: "2027-08-14",
    isNational: true,
    description: "Maulid Nabi Muhammad SAW",
    year: 2027,
  },
  {
    name: "HUT Proklamasi Kemerdekaan RI Ke-82",
    date: "2027-08-17",
    isNational: true,
    description: "Hari Kemerdekaan Republik Indonesia",
    year: 2027,
  },
  {
    name: "Hari Santri Nasional 2027",
    date: "2027-10-22",
    isNational: false,
    description: "Peringatan Hari Santri Nasional Kementerian Agama RI",
    year: 2027,
  },
  {
    name: "Hari Guru Nasional 2027",
    date: "2027-11-25",
    isNational: false,
    description: "Peringatan Hari Guru Nasional",
    year: 2027,
  },
  {
    name: "Hari Raya Natal & Cuti Bersama",
    date: "2027-12-25",
    endDate: "2027-12-26",
    isNational: true,
    description: "Hari Raya Natal dan Cuti Bersama",
    year: 2027,
  },
];

/**
 * Filter Master Holidays by year
 */
export function getKemenagHolidaysByYear(year?: number | "all"): KemenagHolidayPreset[] {
  if (!year || year === "all") {
    return KEMENAG_HOLIDAYS_MASTER;
  }
  return KEMENAG_HOLIDAYS_MASTER.filter((h) => h.year === Number(year));
}
